### ISSUE TITLE
PGM cannot run on SportPaper with Java 17

### ISSUE THREAD

**Issue by calcastor** [PGMDev/PGM#1213]
PGM cannot run with SportPaper using Java 17. This appears to occur [here](https://github.com/PGMDev/PGM/blob/c9c4b3e163abafa3d9622a92d6396125ec2e8a7b/util/src/main/java/tc/oc/pgm/util/nms/v1_8/NMSHacks1_8.java#L842).

```
[20:36:27 ERROR]: Error occurred while enabling PGM v0.16-SNAPSHOT (git-610786e) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at tc.oc.pgm.PGMPlugin.onEnable(PGMPlugin.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:320) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:305) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:264) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:431) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:395) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:350) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:283) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:667) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-b362369-P.7913d6e-SP.fb1eb5c-CB.e1ebe52]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at tc.oc.pgm.util.bukkit.Platform.getNMSHacks(Platform.java:83) ~[?:?]
	at tc.oc.pgm.util.nms.NMSHacks.<clinit>(NMSHacks.java:46) ~[?:?]
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at tc.oc.pgm.util.bukkit.Platform.getNMSHacks(Platform.java:77) ~[?:?]
	at tc.oc.pgm.util.nms.NMSHacks.<clinit>(NMSHacks.java:46) ~[?:?]
	... 12 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: modifiers
	at tc.oc.pgm.util.reflect.ReflectionUtils.getField(ReflectionUtils.java:73) ~[?:?]
	at tc.oc.pgm.util.nms.v1_8.NMSHacks1_8.<init>(NMSHacks1_8.java:842) ~[?:?]
	at tc.oc.pgm.util.nms.v1_8.NMSHacksSportPaper.<init>(NMSHacksSportPaper.java:35) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at tc.oc.pgm.util.bukkit.Platform.getNMSHacks(Platform.java:77) ~[?:?]
	at tc.oc.pgm.util.nms.NMSHacks.<clinit>(NMSHacks.java:46) ~[?:?]
	... 12 more
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
	at tc.oc.pgm.util.reflect.ReflectionUtils.getField(ReflectionUtils.java:69) ~[?:?]
	at tc.oc.pgm.util.nms.v1_8.NMSHacks1_8.<init>(NMSHacks1_8.java:842) ~[?:?]
	at tc.oc.pgm.util.nms.v1_8.NMSHacksSportPaper.<init>(NMSHacksSportPaper.java:35) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at tc.oc.pgm.util.bukkit.Platform.getNMSHacks(Platform.java:77) ~[?:?]
	at tc.oc.pgm.util.nms.NMSHacks.<clinit>(NMSHacks.java:46) ~[?:?]
	... 12 more
```

**Comment by cswhite2000** [comment]
The same code is also present in SportPaper, from paper 1.8 in `PaperSpigotConfig.java`
```java
Field modifiers = Field.class.getDeclaredField("modifiers");
modifiers.setAccessible(true);
modifiers.setInt(maxStack, maxStack.getModifiers() & ~Modifier.FINAL);
```
vs
```java
Field modifiersField = ReflectionUtils.getField(Field.class, "modifiers");
...
modifiersField.setInt(dimensionField, dimensionField.getModifiers() & ~Modifier.FINAL);
dimensionField.set(worldServerField.get(world), 11);
```

Basically, it's updating the internal flag for whether the field is final and then updating the field.
This breaks in java 1.12+ because the final modifier cannot be removed starting in those versions.

**Comment by calcastor** [comment]
Resolved via https://github.com/PGMDev/PGM/pull/1288 and https://github.com/Electroid/SportPaper/pull/139
