### ISSUE TITLE
Teams packet related string created by PGM seems to exceed 16 character limit

### ISSUE THREAD

**Issue by calcastor** [PGMDev/PGM#1454]
```
[00:36:39 WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.RuntimeException: The received string length is longer than maximum allowed (38 > 16)
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:651) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerTeams.read(WrapperPlayServerTeams.java:165) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:277) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:182) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:172) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerTeams.<init>(WrapperPlayServerTeams.java:122) ~[?:?]
	at ac.grim.grimac.utils.team.TeamHandler.onPacketSend(TeamHandler.java:49) ~[?:?]
	at ac.grim.grimac.manager.CheckManager.onPacketSend(CheckManager.java:267) ~[?:?]
	at ac.grim.grimac.events.packets.CheckManagerListener.onPacketSend(CheckManagerListener.java:724) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:61) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:88) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:73) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:52) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:107) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:239) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git-SportPaper-09062d3-P.ec24be5-SP.484b02b-CB.e1ebe52]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```

This occurs with Grim and ViaVersion upon logging onto a PGM server with a 1.21.3 client

**Comment by Pablete1234** [comment]
This is an issue in the interaction between packetevents/viaversion, pgm has no part in this

**Comment by calcastor** [comment]
~~Resolved by https://github.com/PGMDev/PGM/pull/1480~~ nope, mistested

**Comment by Pablete1234** [comment]
No, that's not what #1480 fixes at all. That pr is exclusively fixing a bug related to the new fake player entities introduced in #1479, and this issue preceeds that

**Comment by calcastor** [comment]
Mistested previously; the issue is actually caused by https://github.com/PGMDev/PGM/pull/1338
