### ISSUE TITLE
Exception on cycle bossbar makes it not progress

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#743]
The match ended, bossbar "cycling in 35 seconds" appeared, but never started counting down:

```
[06:17:35] [Server thread/INFO]: Time Remaining: 00:03
[06:17:36] [Server thread/INFO]: Time Remaining: 00:02
[06:17:37] [Server thread/INFO]: Time Remaining: 00:01
[06:17:38] [Server thread/INFO]: [Map Pool] Map pool has been set to hecto in order to better adjust to the current player count.
[06:17:38] [Server thread/ERROR]: Could not pass event MatchFinishEvent to PGM v0.10-SNAPSHOT (git-1bd3939)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:65) ~[sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at tc.oc.pgm.match.MatchImpl$EventExecutor.execute(MatchImpl.java:326) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:65) ~[sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:569) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEventSynchronously(SimplePluginManager.java:527) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:521) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at tc.oc.pgm.match.MatchImpl.callEvent(MatchImpl.java:248) [PGM.jar:?]
        at tc.oc.pgm.match.MatchImpl.setPhase(MatchImpl.java:208) [PGM.jar:?]
        at tc.oc.pgm.match.MatchImpl.finish(MatchImpl.java:380) [PGM.jar:?]
        at tc.oc.pgm.match.MatchImpl.calculateVictory(MatchImpl.java:619) [PGM.jar:?]
        at tc.oc.pgm.timelimit.TimeLimitCountdown.onEnd(TimeLimitCountdown.java:88) [PGM.jar:?]
        at tc.oc.pgm.countdowns.CountdownRunner.run(CountdownRunner.java:142) [PGM.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
        at tc.oc.pgm.util.concurrent.TaskExecutorService$Task.run(TaskExecutorService.java:228) [PGM.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:893) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724) [sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
        at us.myles.ViaVersion.boss.CommonBoss.sendPacketConnection(CommonBoss.java:199) ~[?:?]
        at us.myles.ViaVersion.boss.CommonBoss.addConnection(CommonBoss.java:86) ~[?:?]
        at us.myles.ViaVersion.boss.CommonBoss.addPlayer(CommonBoss.java:80) ~[?:?]
        at tc.oc.pgm.util.bossbar.BossBarViaView.render(BossBarViaView.java:20) ~[?:?]
        at tc.oc.pgm.util.bossbar.BossBarView.invalidate(BossBarView.java:46) ~[?:?]
        at tc.oc.pgm.util.bossbar.DynamicBossBar.invalidate(DynamicBossBar.java:12) ~[?:?]
        at tc.oc.pgm.util.bossbar.BossBarStack.push(BossBarStack.java:43) ~[?:?]
        at tc.oc.pgm.bossbar.BossBarMatchModule.pushBossBar(BossBarMatchModule.java:55) ~[?:?]
        at tc.oc.pgm.bossbar.BossBarMatchModule.pushBossBarIfAbsent(BossBarMatchModule.java:64) ~[?:?]
        at tc.oc.pgm.countdowns.MatchCountdown.showOrHideBossBar(MatchCountdown.java:139) ~[?:?]
        at tc.oc.pgm.countdowns.MatchCountdown.onStart(MatchCountdown.java:87) ~[?:?]
        at tc.oc.pgm.countdowns.CountdownRunner.start(CountdownRunner.java:74) ~[?:?]
        at tc.oc.pgm.countdowns.CountdownContext.start(CountdownContext.java:42) ~[?:?]
        at tc.oc.pgm.countdowns.SingleCountdownContext.start(SingleCountdownContext.java:18) ~[?:?]
        at tc.oc.pgm.countdowns.CountdownContext.start(CountdownContext.java:31) ~[?:?]
        at tc.oc.pgm.countdowns.CountdownContext.start(CountdownContext.java:27) ~[?:?]
        at tc.oc.pgm.cycle.CycleMatchModule.startCountdown(CycleMatchModule.java:38) ~[?:?]
        at tc.oc.pgm.cycle.CycleMatchModule.onMatchEnd(CycleMatchModule.java:60) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[sportpaper.jar:git-SportPaper-v1.0-5-g9203b9c3]
        ... 70 more
[06:17:38] [Server thread/INFO]: _Beeser_ lost connection: Disconnected
```

**Comment by Electroid** [comment]
I suppose this goes away with the `adventure` refactor?
