### ISSUE TITLE
Sidebar not trimming long entries

### ISSUE THREAD

**Issue by Pugzy** [PGMDev/PGM#756]
Caused when trying to display long names on the scoreboard. 
Replicate by setting a shown objective to have a long name. No scoreboard will display.

```java
[MatchManagerImpl] Loaded match-11 (thedropper)
java.lang.IllegalArgumentException: Line 2 is longer than 30 chars
	at fr.mrmicky.fastboard.FastBoard.updateLines(FastBoard.java:261)
	at tc.oc.pgm.scoreboard.SidebarMatchModule.renderSidebar(SidebarMatchModule.java:500)
	at tc.oc.pgm.scoreboard.SidebarMatchModule.lambda$renderSidebarDebounce$0(SidebarMatchModule.java:353)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at tc.oc.pgm.util.concurrent.TaskExecutorService$Task.run(TaskExecutorService.java:228)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64)
```

Would also probs trigger with player names in FFA too.
Maybe the source of the below but not triggering until a player with a long name has either joined or got a scoreboard position.

![image](https://user-images.githubusercontent.com/8608892/103100380-2f2c9400-460a-11eb-8b80-510f415fbfff.png)

**Comment by Pugzy** [comment]
Resolved in https://github.com/PGMDev/PGM/pull/760
