### ISSUE TITLE
Exception on server shutdown

### ISSUE THREAD

**Issue by ghost** [PGMDev/PGM#874]
I get this error when I restart or the server restarts with people inside

```
[09:16:51] [Server thread/ERROR]: Could not pass event PlayerPartyChangeEvent to PGM v0.12-SNAPSHOT (git-405f5f7)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:65) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at tc.oc.pgm.match.MatchImpl$EventExecutor.execute(MatchImpl.java:327) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:65) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:569) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEventSynchronously(SimplePluginManager.java:527) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:521) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at tc.oc.pgm.match.MatchImpl.callEvent(MatchImpl.java:242) ~[?:?]
	at tc.oc.pgm.match.MatchImpl.setOrClearPlayerParty(MatchImpl.java:561) ~[?:?]
	at tc.oc.pgm.match.MatchImpl.removePlayer(MatchImpl.java:450) ~[?:?]
	at tc.oc.pgm.match.MatchImpl.unload(MatchImpl.java:833) ~[?:?]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) [?:?]
	at tc.oc.pgm.PGMPlugin.onDisable(PGMPlugin.java:229) [core-0.12-20210519.013837-18.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:327) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:284) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:480) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:762) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException: Given attachment is not part of Permissible object CraftPlayer{name=Sparkez}
	at org.bukkit.permissions.PermissibleBase.removeAttachment(PermissibleBase.java:149) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.removeAttachment(CraftHumanEntity.java:129) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at tc.oc.pgm.spawns.states.Observing.leaveState(Observing.java:110) ~[?:?]
	at tc.oc.pgm.spawns.SpawnMatchModule.transition(SpawnMatchModule.java:144) ~[?:?]
	at tc.oc.pgm.spawns.SpawnMatchModule.onPartyChange(SpawnMatchModule.java:183) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	... 74 more
```

**Comment by CoWinkKeyDinkInc** [comment]
I haven't gotten this problem. Seems the `isParticipating()` and `isObserving` functions are deprecated.

**Comment by ghost** [comment]
I don't know if it's normal, but rarely when I test on localhost by restarting the server with me inside, I don't get the error, why?

**Comment by CoWinkKeyDinkInc** [comment]
Hmm, perhaps it expects bungeecord or some integration in the Community plugin. Are you using those?

**Comment by ghost** [comment]
Don't use bungee on localhost, so suddenly that's the difference
