### ISSUE TITLE
Error / bug obs

### ISSUE THREAD

**Issue by ghost** [PGMDev/PGM#875]
I get this error, I also want to comment a bug with the observers, when you are a participant sometimes it happens that you can see some observers or all of them.

In the latest version of PGM.

```
[02:08:27] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:916) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823) ~[sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by KingOfSquares** [comment]
This stacktrace does not mention PGM, when do you get the error?

**Comment by Pablete1234** [comment]
PGM is cycling or doing some parts of the cycle in non thread-safe ways, if it so happens that you remove a player while minecraft is iterating the list of players things like these can happen

**Comment by ghost** [comment]
So it's normal that it happens, but it won't happen often, right?

Changing the subject, do you know why I can now see the observers while I am a participant?
Because it didn't happen before
