### ISSUE TITLE
Control Point Tick

### ISSUE THREAD

**Issue by ghost** [PGMDev/PGM#877]
I don't know exactly when the error appeared, but I was testing if it appeared when the point was only left at a certain percentage captured but no, I think the error appears when two players from different teams are in the same point capturing, I'm not 100% sure, but it can be that

```
[23:44:54] [Server thread/ERROR]: [MatchImpl] Could not tick tc.oc.pgm.controlpoint.ControlPointTickTask@55a07afc
java.lang.NullPointerException
	at tc.oc.pgm.controlpoint.ControlPoint.recover(ControlPoint.java:502) ~[core-0.12-20210519.013837-18.jar:?]
	at tc.oc.pgm.controlpoint.ControlPoint.dominate(ControlPoint.java:435) ~[core-0.12-20210519.013837-18.jar:?]
	at tc.oc.pgm.controlpoint.ControlPoint.dominateAndFireEvents(ControlPoint.java:355) ~[core-0.12-20210519.013837-18.jar:?]
	at tc.oc.pgm.controlpoint.ControlPoint.tickCapture(ControlPoint.java:339) ~[core-0.12-20210519.013837-18.jar:?]
	at tc.oc.pgm.controlpoint.ControlPoint.tick(ControlPoint.java:265) ~[core-0.12-20210519.013837-18.jar:?]
	at tc.oc.pgm.controlpoint.ControlPointTickTask.tick(ControlPointTickTask.java:21) ~[core-0.12-20210519.013837-18.jar:?]
	at tc.oc.pgm.match.MatchImpl$TickableTask.run(MatchImpl.java:727) [core-0.12-20210519.013837-18.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at tc.oc.pgm.util.concurrent.TaskExecutorService$Task.run(TaskExecutorService.java:228) [core-0.12-20210519.013837-18.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:893) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724) [sportpaper.jar:git-SportPaper-v1.0-22-g18f33e3]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Pugzy** [comment]
When reporting issues in this way it's very difficult to replicate and debug unless you can provide the exact steps required.

**Comment by Pablete1234** [comment]
Going to ping @mrcookieunderscore13 since this was recently changed.

Some more information or a map would be helpful to debug this @lBoyka

**Comment by ghost** [comment]
In the maps that I got the error was in Limbo II and Ladderp II, anyway I will try to test and record at what time the error occurs

**Comment by ghost** [comment]
I will close this, since it seems that the problem was fixed with yesterday's update, it no longer comes out those errors in Capture the point.

Also, sorry, I didn't have time to record.
